/**
 * Mock product data for when live scraping is unavailable
 * (e.g., in sandbox environments without full network access)
 * Simulates real-world data structure faithfully
 */

function generateMockProducts(query) {
  const q = query.toLowerCase();

  const datasets = {
    headphones: headphonesData,
    earphones: headphonesData,
    earbuds: earbudsData,
    wireless: earbudsData,
    laptop: laptopData,
    phone: phoneData,
    iphone: phoneData,
    samsung: phoneData,
    oneplus: phoneData,
    tv: tvData,
    television: tvData,
    watch: watchData,
    smartwatch: watchData,
  };

  // Find best matching dataset
  const key = Object.keys(datasets).find((k) => q.includes(k));
  const data = key ? datasets[key] : genericData(query);

  // Simulate slight delay/variation
  return data.map((p) => ({
    ...p,
    price: p.price ? p.price + Math.floor(Math.random() * 100 - 50) : null,
  }));
}

const headphonesData = [
  {
    id: 'amazon_B09XS7JWHH',
    platform: 'Amazon',
    asin: 'B09XS7JWHH',
    title: 'Sony WH-1000XM5 Wireless Industry Leading Noise Canceling Headphones with Auto Noise Canceling Optimizer, Crystal Clear Hands-Free Calling, and Alexa Voice Control, Black',
    image: 'https://m.media-amazon.com/images/I/51aXvjzcukL._AC_SL1500_.jpg',
    price: 29990,
    rating: 4.4,
    reviews: 8924,
    availability: 'In Stock',
    delivery: 'FREE delivery Tomorrow',
    url: 'https://www.amazon.in/dp/B09XS7JWHH',
  },
  {
    id: 'flipkart_ACCGWFGCJB2F3HRD',
    platform: 'Flipkart',
    pid: 'ACCGWFGCJB2F3HRD',
    title: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones Over Ear Bluetooth 30Hr Battery with mic for Phone Calls, Black',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/t/9/2/wh-1000xm5-sony-original-imaghx3kysfkmbnn.jpeg',
    price: 27990,
    rating: 4.3,
    reviews: 5621,
    availability: 'In Stock',
    delivery: 'Delivery by Tomorrow',
    url: 'https://www.flipkart.com/sony-wh-1000xm5-wireless-industry-leading-noise-canceling-headphones/p/ACCGWFGCJB2F3HRD',
  },
  {
    id: 'amazon_B0BPKR97YK',
    platform: 'Amazon',
    asin: 'B0BPKR97YK',
    title: 'Bose QuietComfort 45 Bluetooth Wireless Noise Cancelling Headphones - Triple Black',
    image: 'https://m.media-amazon.com/images/I/51Y2CGBE3+L._AC_SL1500_.jpg',
    price: 24990,
    rating: 4.5,
    reviews: 12450,
    availability: 'In Stock',
    delivery: 'FREE delivery Tomorrow',
    url: 'https://www.amazon.in/dp/B0BPKR97YK',
  },
  {
    id: 'flipkart_ACCFNDNJZQNZKTYF',
    platform: 'Flipkart',
    pid: 'ACCFNDNJZQNZKTYF',
    title: 'Bose QuietComfort 45 Bluetooth Wireless Over Ear Headphones with Noise Cancelling - Triple Black',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/p/m/s/quietcomfort-45-bose-original-imagfg3hvnpf4ghg.jpeg',
    price: 25490,
    rating: 4.4,
    reviews: 8230,
    availability: 'In Stock',
    delivery: 'Delivery in 2 days',
    url: 'https://www.flipkart.com/bose-quietcomfort-45-bluetooth-wireless-over-ear-headphones/p/ACCFNDNJZQNZKTYF',
  },
  {
    id: 'amazon_B09YJX38BJ',
    platform: 'Amazon',
    asin: 'B09YJX38BJ',
    title: 'boAt Rockerz 550 Bluetooth Headphone with 20 Hours Playback, 40mm Dynamic Driver, Soft Padded Ear Cushions and Foldable Design (Luscious Black)',
    image: 'https://m.media-amazon.com/images/I/61k4jNhT8cL._SL1500_.jpg',
    price: 1299,
    rating: 4.1,
    reviews: 45200,
    availability: 'In Stock',
    delivery: 'FREE delivery Tomorrow',
    url: 'https://www.amazon.in/dp/B09YJX38BJ',
  },
  {
    id: 'flipkart_ACCFB5SHQ2XHHW9Z',
    platform: 'Flipkart',
    pid: 'ACCFB5SHQ2XHHW9Z',
    title: 'boAt Rockerz 550 Bluetooth Headphone 20 Hours Playback with Foldable Design (Luscious Black)',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/c/f/r/rockerz-550-boat-original-imagg7vyhzgtdswp.jpeg',
    price: 1249,
    rating: 4.0,
    reviews: 38900,
    availability: 'In Stock',
    delivery: 'Delivery Tomorrow',
    url: 'https://www.flipkart.com/boat-rockerz-550-bluetooth-headphone/p/ACCFB5SHQ2XHHW9Z',
  },
  {
    id: 'amazon_B09B8H3FGJ',
    platform: 'Amazon',
    asin: 'B09B8H3FGJ',
    title: 'JBL Tune 770NC Adaptive Noise Cancelling Wireless Over-Ear Headphones, 70H Battery, Speed Charge, Foldable Design, Black',
    image: 'https://m.media-amazon.com/images/I/51nE5OFf5gL._AC_SL1500_.jpg',
    price: 5999,
    rating: 4.2,
    reviews: 7821,
    availability: 'In Stock',
    delivery: 'FREE delivery in 2 days',
    url: 'https://www.amazon.in/dp/B09B8H3FGJ',
  },
  {
    id: 'amazon_B09JQMJHXY',
    platform: 'Amazon',
    asin: 'B09JQMJHXY',
    title: 'Sennheiser MOMENTUM 4 Wireless Headphones - Adaptive Noise Cancellation, 60-Hour Battery Life, Bluetooth 5.2 - Black',
    image: 'https://m.media-amazon.com/images/I/71PY4+b8wKL._AC_SL1500_.jpg',
    price: 19990,
    rating: 4.3,
    reviews: 3241,
    availability: 'In Stock',
    delivery: 'FREE delivery Tomorrow',
    url: 'https://www.amazon.in/dp/B09JQMJHXY',
  },
];

const earbudsData = [
  {
    id: 'amazon_B0CHX2TFQ5',
    platform: 'Amazon',
    asin: 'B0CHX2TFQ5',
    title: 'OnePlus Nord Buds 3 Pro True Wireless Earbuds with Up to 49dB Adaptive Noise Cancellation, 10 mins = 5 Hours Charging, Spatial Audio, IP55 Rating',
    image: 'https://m.media-amazon.com/images/I/61g+L1rlp+L._SL1500_.jpg',
    price: 3999,
    rating: 4.3,
    reviews: 6720,
    availability: 'In Stock',
    delivery: 'FREE delivery Tomorrow',
    url: 'https://www.amazon.in/dp/B0CHX2TFQ5',
  },
  {
    id: 'flipkart_ACCGBHHYEACNFTZB',
    platform: 'Flipkart',
    pid: 'ACCGBHHYEACNFTZB',
    title: 'OnePlus Nord Buds 3 Pro ANC Earbuds 49dB Noise Cancellation IP55 Spatial Audio',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/v/h/d/-original-imagtey95gxzv2fq.jpeg',
    price: 3799,
    rating: 4.2,
    reviews: 4215,
    availability: 'In Stock',
    delivery: 'Delivery by Tomorrow',
    url: 'https://www.flipkart.com/oneplus-nord-buds-3-pro-bluetooth-headset/p/ACCGBHHYEACNFTZB',
  },
  {
    id: 'amazon_B09G9HD6PD',
    platform: 'Amazon',
    asin: 'B09G9HD6PD',
    title: 'boAt Airdopes 141 Bluetooth Truly Wireless in Ear Earbuds with mic, 42H Playtime, ENx Tech, Beast Mode (Low Latency Upto 60ms), ASAP Charge, IPX4, BT v5.1 (Bold Black)',
    image: 'https://m.media-amazon.com/images/I/51FyMjxYsiL._SL1500_.jpg',
    price: 999,
    rating: 4.1,
    reviews: 158000,
    availability: 'In Stock',
    delivery: 'FREE delivery Tomorrow',
    url: 'https://www.amazon.in/dp/B09G9HD6PD',
  },
  {
    id: 'flipkart_ACCF35GVHUHKXF7E',
    platform: 'Flipkart',
    pid: 'ACCF35GVHUHKXF7E',
    title: 'boAt Airdopes 141 Bluetooth TWS Earbuds 42H Playtime ENx Tech ASAP Charge IPX4 Bold Black',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/b/o/e/airdopes-141-boat-original-imagfyqwkghcvzrd.jpeg',
    price: 899,
    rating: 4.0,
    reviews: 120500,
    availability: 'In Stock',
    delivery: 'Delivery Tomorrow',
    url: 'https://www.flipkart.com/boat-airdopes-141-bluetooth-headset/p/ACCF35GVHUHKXF7E',
  },
  {
    id: 'amazon_B0C62MX6ZX',
    platform: 'Amazon',
    asin: 'B0C62MX6ZX',
    title: 'Apple AirPods Pro (2nd Generation) Wireless Earbuds, Up to 2X More Active Noise Cancelling, Adaptive Transparency, Personalized Spatial Audio, MagSafe USB-C Charging Case',
    image: 'https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_SL1500_.jpg',
    price: 24900,
    rating: 4.6,
    reviews: 28700,
    availability: 'In Stock',
    delivery: 'FREE delivery Tomorrow',
    url: 'https://www.amazon.in/dp/B0C62MX6ZX',
  },
  {
    id: 'flipkart_ACCGQW3AAQKXSNQ4',
    platform: 'Flipkart',
    pid: 'ACCGQW3AAQKXSNQ4',
    title: 'Apple AirPods Pro 2nd Generation USB-C MagSafe Charging Case with Active Noise Cancellation',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/x/u/9/airpods-pro-2nd-gen-usb-c-apple-original-imagpnpyyj2wr2yt.jpeg',
    price: 24400,
    rating: 4.5,
    reviews: 18200,
    availability: 'In Stock',
    delivery: 'Delivery Tomorrow',
    url: 'https://www.flipkart.com/apple-airpods-pro-2nd-gen/p/ACCGQW3AAQKXSNQ4',
  },
];

const laptopData = [
  {
    id: 'amazon_B0CHF7B95H',
    platform: 'Amazon',
    asin: 'B0CHF7B95H',
    title: 'ASUS Vivobook 15 (2023) Intel Core i3-1215U 15.6-inch (39.62 cm) Full HD Thin and Light Laptop (8GB/512GB SSD/Windows 11/Backlit Keyboard/Office 2021/Silver/1.7 kg)',
    image: 'https://m.media-amazon.com/images/I/81FJPcoFysL._SL1500_.jpg',
    price: 36990,
    rating: 4.2,
    reviews: 5830,
    availability: 'In Stock',
    delivery: 'FREE delivery in 2-3 days',
    url: 'https://www.amazon.in/dp/B0CHF7B95H',
  },
  {
    id: 'flipkart_COMGSPUZYZRJNTZZ',
    platform: 'Flipkart',
    pid: 'COMGSPUZYZRJNTZZ',
    title: 'ASUS VivoBook 15 Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) X1504ZA-BQ322WS Laptop (15.6 inch, Silver, 1.7 Kg, With MS Office)',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/computer/l/q/f/-original-imagtddmzxymqchd.jpeg',
    price: 35490,
    rating: 4.2,
    reviews: 4210,
    availability: 'In Stock',
    delivery: 'Delivery in 2 days',
    url: 'https://www.flipkart.com/asus-vivobook-15-core-i3-12th-gen/p/COMGSPUZYZRJNTZZ',
  },
  {
    id: 'amazon_B0CG4VG7Z9',
    platform: 'Amazon',
    asin: 'B0CG4VG7Z9',
    title: 'Lenovo IdeaPad Slim 3 Intel Core i5-12450H 15.6-inch (39.62 cm) FHD IPS 300Nits Thin & Light Laptop (16GB/512GB SSD/Windows 11/Alexa/Office 2021/3 Month Game Pass/Grey/1.62Kg)',
    image: 'https://m.media-amazon.com/images/I/71y5GCRA1WL._SL1500_.jpg',
    price: 54990,
    rating: 4.3,
    reviews: 9241,
    availability: 'In Stock',
    delivery: 'FREE delivery Tomorrow',
    url: 'https://www.amazon.in/dp/B0CG4VG7Z9',
  },
  {
    id: 'flipkart_COMGTQF9HCVZHD3K',
    platform: 'Flipkart',
    pid: 'COMGTQF9HCVZHD3K',
    title: 'Lenovo IdeaPad Slim 3 Core i5 12th Gen 12450H - (16 GB/512 GB SSD/Windows 11 Home) 82XB00FBIN Laptop (15.6 inch, Arctic Grey, 1.62 Kg, With MS Office)',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/computer/k/v/x/-original-imagsyfrnxkxrqze.jpeg',
    price: 52990,
    rating: 4.3,
    reviews: 7180,
    availability: 'In Stock',
    delivery: 'Delivery in 2 days',
    url: 'https://www.flipkart.com/lenovo-ideapad-slim-3-core-i5-12th-gen/p/COMGTQF9HCVZHD3K',
  },
];

const phoneData = [
  {
    id: 'amazon_B0CHX3QBCH',
    platform: 'Amazon',
    asin: 'B0CHX3QBCH',
    title: 'OnePlus 12 5G (Flowy Emerald, 12GB RAM, 256GB Storage)',
    image: 'https://m.media-amazon.com/images/I/71U2kPQXRKL._SL1500_.jpg',
    price: 64999,
    rating: 4.4,
    reviews: 18200,
    availability: 'In Stock',
    delivery: 'FREE delivery Tomorrow',
    url: 'https://www.amazon.in/dp/B0CHX3QBCH',
  },
  {
    id: 'flipkart_MOBGXPHZYDVKHEPJ',
    platform: 'Flipkart',
    pid: 'MOBGXPHZYDVKHEPJ',
    title: 'OnePlus 12 5G (Flowy Emerald, 12 GB RAM, 256 GB Storage)',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/c/a/d/-original-imagtzfdmx2v9dng.jpeg',
    price: 62999,
    rating: 4.3,
    reviews: 13400,
    availability: 'In Stock',
    delivery: 'Delivery Tomorrow',
    url: 'https://www.flipkart.com/oneplus-12-5g/p/MOBGXPHZYDVKHEPJ',
  },
  {
    id: 'amazon_B0CQTTG5JC',
    platform: 'Amazon',
    asin: 'B0CQTTG5JC',
    title: 'Samsung Galaxy S24 5G AI Smartphone (Onyx Black, 8GB, 256GB Storage)',
    image: 'https://m.media-amazon.com/images/I/71oRFGjhUxL._SL1500_.jpg',
    price: 74999,
    rating: 4.4,
    reviews: 9860,
    availability: 'In Stock',
    delivery: 'FREE delivery Tomorrow',
    url: 'https://www.amazon.in/dp/B0CQTTG5JC',
  },
  {
    id: 'flipkart_MOBGYTFFHKAQHPFU',
    platform: 'Flipkart',
    pid: 'MOBGYTFFHKAQHPFU',
    title: 'SAMSUNG Galaxy S24 5G (Onyx Black, 256 GB) (8 GB RAM)',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/f/9/i/-original-imagtnggzdahqgrz.jpeg',
    price: 72999,
    rating: 4.3,
    reviews: 7640,
    availability: 'In Stock',
    delivery: 'Delivery Tomorrow',
    url: 'https://www.flipkart.com/samsung-galaxy-s24-5g/p/MOBGYTFFHKAQHPFU',
  },
  {
    id: 'amazon_B0CTBWT56C',
    platform: 'Amazon',
    asin: 'B0CTBWT56C',
    title: 'Redmi Note 13 Pro+ 5G (Fusion Black, 12GB RAM, 256GB Storage) | 200MP OIS Camera | 120W HyperCharge | Curved AMOLED Display',
    image: 'https://m.media-amazon.com/images/I/71QNGq0KDNL._SL1500_.jpg',
    price: 31999,
    rating: 4.3,
    reviews: 28300,
    availability: 'In Stock',
    delivery: 'FREE delivery Tomorrow',
    url: 'https://www.amazon.in/dp/B0CTBWT56C',
  },
  {
    id: 'flipkart_MOBGVXG2XNVHZFGH',
    platform: 'Flipkart',
    pid: 'MOBGVXG2XNVHZFGH',
    title: 'Redmi Note 13 Pro+ 5G (Fusion Black, 256 GB) (12 GB RAM)',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/mobile/c/j/i/-original-imagr5hhhefxmzmd.jpeg',
    price: 30999,
    rating: 4.3,
    reviews: 22100,
    availability: 'In Stock',
    delivery: 'Delivery Tomorrow',
    url: 'https://www.flipkart.com/redmi-note-13-pro-5g/p/MOBGVXG2XNVHZFGH',
  },
];

const tvData = [
  {
    id: 'amazon_B0C6Y2JFX4',
    platform: 'Amazon',
    asin: 'B0C6Y2JFX4',
    title: 'LG 139 cm (55 inches) 4K Ultra HD Smart OLED TV 55C3PSA (Dark Steel Silver)',
    image: 'https://m.media-amazon.com/images/I/71y8SDpMJVL._SL1500_.jpg',
    price: 134990,
    rating: 4.5,
    reviews: 4320,
    availability: 'In Stock',
    delivery: 'FREE delivery in 3-5 days',
    url: 'https://www.amazon.in/dp/B0C6Y2JFX4',
  },
  {
    id: 'flipkart_TVSGHHFRZPKYGFMQ',
    platform: 'Flipkart',
    pid: 'TVSGHHFRZPKYGFMQ',
    title: 'LG 55 inches 4K Ultra HD Smart OLED TV (55C3PSA)',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/television/v/i/w/-original-imagtfugghfzh2bq.jpeg',
    price: 129990,
    rating: 4.4,
    reviews: 3180,
    availability: 'In Stock',
    delivery: 'Delivery in 5-7 days',
    url: 'https://www.flipkart.com/lg-139-cm-55-inches-4k-ultra-hd-oled-tv/p/TVSGHHFRZPKYGFMQ',
  },
];

const watchData = [
  {
    id: 'amazon_B0C3BQNSZJ',
    platform: 'Amazon',
    asin: 'B0C3BQNSZJ',
    title: 'Noise ColorFit Ultra 3 Smart Watch with 1.96" AMOLED Display, Bluetooth Calling, Built-in Alexa, 100+ Sports Modes, Health Tracking, IP68',
    image: 'https://m.media-amazon.com/images/I/71g5kRalMrL._SL1500_.jpg',
    price: 3999,
    rating: 4.1,
    reviews: 42100,
    availability: 'In Stock',
    delivery: 'FREE delivery Tomorrow',
    url: 'https://www.amazon.in/dp/B0C3BQNSZJ',
  },
  {
    id: 'flipkart_SMWGHHYNZAHHYZRB',
    platform: 'Flipkart',
    pid: 'SMWGHHYNZAHHYZRB',
    title: 'Noise ColorFit Ultra 3 Smartwatch AMOLED Display Bluetooth Calling Built-in Alexa 100+ Sports Modes IP68',
    image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/smartwatch/9/j/4/-original-imagtnyewfmpwqvt.jpeg',
    price: 3799,
    rating: 4.0,
    reviews: 34500,
    availability: 'In Stock',
    delivery: 'Delivery Tomorrow',
    url: 'https://www.flipkart.com/noise-colorfit-ultra-3-smartwatch/p/SMWGHHYNZAHHYZRB',
  },
];

function genericData(query) {
  return [
    {
      id: 'amazon_B09GENERIC01',
      platform: 'Amazon',
      asin: 'B09GENERIC01',
      title: `${query} - Premium Quality Product (Amazon)`,
      image: 'https://m.media-amazon.com/images/I/61k4jNhT8cL._SL1500_.jpg',
      price: 4999,
      rating: 4.2,
      reviews: 1250,
      availability: 'In Stock',
      delivery: 'FREE delivery Tomorrow',
      url: `https://www.amazon.in/s?k=${encodeURIComponent(query)}`,
    },
    {
      id: 'flipkart_FK09GENERIC01',
      platform: 'Flipkart',
      pid: 'FK09GENERIC01',
      title: `${query} - Best Deal (Flipkart)`,
      image: 'https://rukminim2.flixcart.com/image/416/416/xif0q/headphone/b/o/e/airdopes-141-boat-original-imagfyqwkghcvzrd.jpeg',
      price: 4799,
      rating: 4.1,
      reviews: 980,
      availability: 'In Stock',
      delivery: 'Delivery Tomorrow',
      url: `https://www.flipkart.com/search?q=${encodeURIComponent(query)}`,
    },
  ];
}

module.exports = { generateMockProducts };
